name: shocase
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  geolocator: ^7.2.0+1
  location: ^4.3.0
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  firebase_database: ^7.1.1
  firebase_storage: ^10.0.1
  geocoding: ^2.0.0
  geoflutterfire: ^3.0.1
  rxdart: ^0.27.0
  fluttertoast: ^8.0.7
  carousel_slider: ^4.0.0
  flutter_svg: ^0.22.0
  convex_bottom_bar: ^3.0.0
  provider: ^5.0.0
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^6.1.0
  intl: ^0.17.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  checkbox_formfield: ^0.1.0+3
  image_picker: ^0.8.3+2
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/cover.png
    - assets/logo.png
    - assets/map.png
    - assets/headerlogo.png
    - assets/add.png
    - assets/


  # example:
  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: MyFlutterApp
      fonts:
         - asset: assets/MyFlutterApp.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
